routes/web.php
<?php

// a testing route to find post-category-tag relationships
Route::get('/test',function(){
        //find PostCategory of id = 1 and look into its associated Post
        // return App\PostCategory::find(1)->posts;
        //find Tag of id = 1 and look into its associated Post
        // App\Tag::find(1)->posts;
        return App\Profile::find(1)->user;

});


Route::get('/',[

        'uses'=>'FrontEndController@index',
        'as' => 'index'
]); 

Auth::routes(); 

//Admin 
Route::group(['prefix' => 'vathos', 'middleware' => 'auth'], function () {

Route::get('/', 'HomeController@index') -> name('home'); 

Route::get('/posts', [
    'uses' => 'PostsController@index',
'as' => 'posts'
]); 
Route::get('/posts/trashed', [
        'uses' => 'PostsController@trashed', 
'as' => 'posts.trashed'
]); 

Route::get('/post/edit/{id}', [
        
            'uses' => 'PostsController@edit', 
'as' => 'post.edit'
]); 
Route::post('/post/update/{id}', [
                    'uses' => 'PostsController@update', 
'as' => 'post.update'
]); 

Route::get('/post/create', [

    'uses' => 'PostsController@create', 
'as' => 'post.create'
]); 

Route::post('/post/store', [

    'uses' => 'PostsController@store', 
'as' => 'post.store'
]); 

Route::get('/post/delete/{id}', [
        
            'uses' => 'PostsController@delete', 
'as' => 'post.delete'
]); 

Route::get('/post/kill/{id}', [
        'uses' => 'PostsController@kill', 
'as' => 'post.kill'
]); 

Route::get('/post/restore/{id}', [
        'uses' => 'PostsController@restore', 
'as' => 'post.restore'
]); 

// Post Category

Route::get('/post_categories', [
        'uses' => 'PostCategoriesController@index', 
'as' => 'post_categories'
]); 

Route::get('/post_category/create', [

    'uses' => 'PostCategoriesController@create', 
'as' => 'post_category.create'
]); 

Route::post('/post_category/store', [

    'uses' => 'PostCategoriesController@store', 
'as' => 'post_category.store'
]); 

Route::get('/post_category/edit/{id}', [
        'uses' => 'PostCategoriesController@edit', 
'as' => 'post_category.edit'
]); 

Route::get('/post_category/delete/{id}', [
        'uses' => 'PostCategoriesController@delete', 
'as' => 'post_category.delete'
]); 

Route::post('/post_category/update/{id}', [
        
            'uses' => 'PostCategoriesController@update', 
'as' => 'post_category.update'
]); 

//Users & Profile
Route::get('/users', [
        'uses' => 'UsersController@index', 
'as' => 'users'
]);
Route::get('/user/create', [
        'uses' => 'UsersController@create', 
'as' => 'user.create'
]);

Route::post('/user/store', [
        'uses' => 'UsersController@store', 
'as' => 'user.store'
]);

Route::get('/user/edit/{id}', [
        'uses' => 'UsersController@edit', 
'as' => 'user.edit'
]);

Route::get('/user/delete/{id}', [
        'uses' => 'UsersController@delete', 
'as' => 'user.delete'
]);

Route::get('user/profile',[
        'uses'=> 'ProfilesController@index',
        'as' => 'user.profile'
]);
Route::post('user/profile/update',[
        'uses'=> 'ProfilesController@update',
        'as' => 'user.profile.update'
]);

//Attach this route to Admin middleware
Route::get('/user/admin/{id}', [
        'uses' => 'UsersController@admin',
        'as' => 'user.admin'
])->middleware('admin');

Route::get('/user/non-admin/{id}', [
        'uses' => 'UsersController@non_admin',
        'as' => 'user.non_admin'
])->middleware('admin');

//Tags

Route::get('/tags',[
        'uses' => 'TagsController@index',
        'as' => 'tags'
        ]);
        
        Route::get('/tag/read/{id}',[
                'uses' => 'TagsController@show',
                'as' => 'tag.show'
                ]);
        
        Route::get('/tag/create',[
                'uses' => 'TagsController@create',
                'as' => 'tag.create'
                ]);
        
        Route::post('/tag/store',[
                'uses' => 'TagsController@store',
                'as' => 'tag.store'
                ]);
        
        Route::get('/tag/edit/{id}',[
                'uses' => 'TagsController@edit',
                'as' => 'tag.edit'
                ]);
        Route::post('/tag/update/{id}',[
                'uses' => 'TagsController@update',
                'as' => 'tag.update'
                ]);
        
        Route::get('/tag/destroy/{id}',[
                'uses'=>'TagsController@destroy',
                'as' =>'tag.destroy'
        ]);

        //Settings
        Route::get('/settings',[
                'uses'=>'SettingsController@index',
                'as' =>'settings.index'
        ]);
        Route::post('/settings/update',[
               'uses'=>'SettingsController@update',
                'as' =>'settings.update' 
        ]);

        Route::get('/message',function(){
                return Message::display();
        });

        Route::resource('portfolios','PortfoliosController');
}); 

app/Portfolio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Portfolio extends Model
{
    protected $fillable = ['title','content'];
}

app/Http/Controllers/PortfoliosController.php
<?php

namespace App\Http\Controllers;

use Session;
use App\Portfolio;
use Illuminate\Http\Request;

class PortfoliosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.portfolios.index')->with('portfolios', Portfolio::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.portfolios.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title' => 'required|min:3',
            'content' => 'required'
        ]);
        Portfolio::create([
            'title' => $request->title,
            'content' => $request->content
        ]);

        Session::flash('success', 'Portfolio created successfully');
        return redirect()->route('portfolios.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/portfolios/create.blade.php
@extends('backend.master') 
@section('content')
<div class="row">
	<div class="col-lg-12">
		<div class="element-wrapper">
			<h6 class="element-header">
				Create New Portolio
			</h6>
			<div class="element-box">
				<form action="{{route('portfolios.store')}}" method="post" enctype="multipart/form-data">
					{{csrf_field()}}
					<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
						<label for=""> Title</label>
						<input name="title" type="text" class="form-control"> 
            @if ($errors->has('title'))
						<span class="help-block text-danger">
							<strong>{{ $errors->first('title') }}</strong>
						</span>
						@endif
					</div>				
					<div class="form-group{{ $errors->has('content') ? ' has-error' : '' }}">
						<label for="">
							Content
						</label>
						<textarea class="form-control" name="content" id="content" cols="30" rows="10"></textarea>						
            @if ($errors->has('content'))
						<span class="help-block text-danger">
							<strong>{{ $errors->first('content') }}</strong>
						</span>
						@endif
					</div>
					<div class="form-buttons-w">
						<button class="btn btn-primary" type="submit"> Save</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
@stop


@section('ckeditor-js')
 <script src="https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.2/classic/ckeditor.js"></script>
<script>
ClassicEditor
    .create( document.querySelector( '#content' ) )
    .then( editor => {
        console.log( editor );
    } )
    .catch( error => {
        console.error( error );
    } );
</script>
@stop

resources/views/backend/portfolios/index.blade.php
@extends('backend.master') 
@section('content')
<div class="row">
	<div class="col-sm-12">
		<div class="element-wrapper">
			<h6 class="element-header">
				Portfolios
			</h6>
			<div class="element-box">

				<div class="table-responsive">
					<table id="datatable" class="table table-striped ">
						<thead>
							<tr>
								<th>#</th>
								<th>Title</th>
								<th>Content</th>								
							</tr>
						</thead>
						<tbody>
							@foreach($portfolios as $key=>$portfolio)
							<tr>
								<td>{{++$key}}</td>
								<td>
									{{$portfolio->title}}
								</td>
								<td>{{$portfolio->content}}</td>								
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection